apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: dma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
        - name: service-b
          image: damienmathieu/service-b:latest
          ports:
            - containerPort: 8080
          env:
            - name: SERVICE_A_URL
              value: http://service-a.dma.svc.cluster.local:80
          livenessProbe:
            httpGet:
              path: /hello
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /hello
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: dma
spec:
  selector:
    app: service-b
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
